"use client"

import Image from "next/image"
import Link from "next/link"
import { Minus, Plus, Trash2 } from "lucide-react"
import { Header } from "@/components/header"
import { Footer } from "@/components/footer"
import { formatPrice, useCart } from "@/components/cart-context"

export default function CartPage() { const { items, total, updateQuantity, removeItem } = useCart(); return <div className="min-h-screen flex flex-col"><Header /><main className="flex-1 container mx-auto px-4 lg:px-8 py-12"><p className="text-xs tracking-[0.25em] text-muted-foreground mb-3">NEXUS STORE</p><h1 className="text-3xl lg:text-4xl font-bold mb-10">SEU CARRINHO</h1>{items.length === 0 ? <div className="border border-border p-12 text-center"><p className="text-muted-foreground mb-6">Seu carrinho está vazio.</p><Link href="/produto" className="inline-flex bg-foreground text-background px-6 py-3 text-sm font-medium">EXPLORAR PRODUTOS</Link></div> : <div className="grid lg:grid-cols-[1fr_360px] gap-10"><div className="space-y-5">{items.map((item) => <div key={item.id} className="flex gap-4 border-b border-border pb-5"><div className="relative w-28 h-36 bg-muted shrink-0"><Image src={item.image} alt={item.name} fill className="object-cover" /></div><div className="flex-1"><h2 className="font-medium mb-2">{item.name}</h2><p className="text-sm text-muted-foreground mb-3">Tamanho: {item.size}</p><p className="font-medium">{formatPrice(item.price)}</p><div className="flex items-center justify-between mt-5"><div className="flex items-center border border-border"><button onClick={() => updateQuantity(item.id, item.quantity - 1)} className="p-2" aria-label="Diminuir quantidade"><Minus className="h-3 w-3" /></button><span className="w-7 text-center text-sm">{item.quantity}</span><button onClick={() => updateQuantity(item.id, item.quantity + 1)} className="p-2" aria-label="Aumentar quantidade"><Plus className="h-3 w-3" /></button></div><button onClick={() => removeItem(item.id)} className="text-muted-foreground hover:text-foreground" aria-label="Remover item"><Trash2 className="h-4 w-4" /></button></div></div></div>)}</div><div className="border border-border p-6 h-fit"><h2 className="font-semibold text-lg mb-6">RESUMO DO PEDIDO</h2><div className="flex justify-between text-sm mb-3"><span>Subtotal</span><span>{formatPrice(total)}</span></div><div className="flex justify-between text-sm border-b border-border pb-5"><span>Frete</span><span>{total >= 199 ? "Grátis" : "Calculado no checkout"}</span></div><div className="flex justify-between font-semibold text-lg py-5"><span>Total</span><span>{formatPrice(total)}</span></div><button className="w-full bg-foreground text-background py-4 text-sm font-medium">FINALIZAR COMPRA</button></div></div>}</main><Footer /></div> }
